### ISSUE TITLE
RuntimeError: outerNode->outputs().size() == node->inputs().size()

### ISSUE THREAD

**Issue by Gaoee** [thb1314/maskrcnn-tensorrt#1]
运行  python codes/002export_onnx.py出现如下问题：
```
%23345 : int[] = prim::ListConstruct(%22531, %23135, %23340, %23344), scope: mmdet.models.detectors.mask_rcnn.MaskRCNN::
  %23346 : Float(1, 100, 800, 1216, strides=[97280000, 972800, 1216, 1], requires_grad=0, device=cpu) = aten::reshape(%23336, %23345), scope: mmdet.models.detectors.mask_rcnn.MaskRCNN:: # /home/ligao/code/maskrcnn_tensorrt/mmdetection/mmdet/models/roi_heads/standard_roi_head.py:347:0
  %7868 : (Float(1, 100, 5, strides=[500, 5, 1], requires_grad=1, device=cpu), Long(1, 100, strides=[100, 1], requires_grad=0, device=cpu), Float(1, 100, 800, 1216, strides=[97280000, 972800, 1216, 1], requires_grad=0, device=cpu)) = prim::TupleConstruct(%det_bboxes.1, %det_labels.1, %23346)
  return (%det_bboxes.1, %det_labels.1, %23346)

Traceback (most recent call last):
  File "codes/002export_onnx.py", line 344, in <module>
    force_write=True)
  File "codes/002export_onnx.py", line 102, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/home/ligao/anaconda3/envs/mmdet_test/lib/python3.7/site-packages/torch/onnx/utils.py", line 519, in export
    export_modules_as_functions=export_modules_as_functions,
  File "/home/ligao/anaconda3/envs/mmdet_test/lib/python3.7/site-packages/torch/onnx/utils.py", line 1539, in _export
    dynamic_axes=dynamic_axes,
  File "/home/ligao/anaconda3/envs/mmdet_test/lib/python3.7/site-packages/torch/onnx/utils.py", line 1123, in _model_to_graph
    module=module,
  File "/home/ligao/anaconda3/envs/mmdet_test/lib/python3.7/site-packages/torch/onnx/utils.py", line 582, in _optimize_graph
    _C._jit_pass_lower_all_tuples(graph)
RuntimeError: outerNode->outputs().size() == node->inputs().size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/dead_code_elimination.cpp":140, please report a bug to PyTorch.
```
请问是什么原因呢

**Comment by thb1314** [comment]
估计是pytorch版本问题

**Comment by Ochre-amber** [comment]
请问最后解决了吗？我也遇到了同样的问题。@Gaoee
我的设备是Jetson AGX ORIN，pytorch版本由Jatpack下载的版本决定，修改pytorch版本不太容易。
